### ISSUE TITLE
Steam Cleaner Spawn

### ISSUE THREAD

**Issue by jefferyrlc** [eraffxi-personal/LSB#12]
Steam Cleaner is just spawning and not from a Detector per Retail Behavior

![Screenshot_20220427_154208](https://user-images.githubusercontent.com/18264856/165614161-15f98108-ee33-4974-8379-ec821b17e99b.png)

**Comment by bsips** [comment]
need documentation on spawn rate from detector

**Comment by jefferyrlc** [comment]
> need documentation on spawn rate from detector

https://www.bg-wiki.com/ffxi/Steam_Cleaner
https://ffxiclopedia.fandom.com/wiki/Steam_Cleaner?so=search

**Comment by bsips** [comment]
todo: 
**Steam_Cleaner.lua:** 
- onmobdeath set server variable for next available SC pop (2-4 hours)
- remove classic NM style respawn time. Double check db values aren't setting this as well so that SC is not freely spawning.

**ids.lua:** 
- table ids for detectors that can spawn SC

**detector.lua**
- spawn no more than 5 adds for each detector, with a chance of popping SC if os.time > server variable and mobid is contained in tabled ids.

**Comment by bsips** [comment]
![image](https://user-images.githubusercontent.com/651924/165642698-d4e93254-9bbe-4334-868c-839e5acdca65.png)
its a party up in here.
